
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Herrera
 */
public class Principal7 extends javax.swing.JFrame {

    /**
     * Creates new form Principal7
     */
    public Principal7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroDePalabras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTamañoEnCm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroDeColores = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValorPalabras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValorTamaño = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValorColores = new javax.swing.JTextField();
        cmbCalcular = new javax.swing.JButton();
        cmbBorrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JasmineUPC", 3, 24)); // NOI18N
        jLabel1.setText("EL PERIÓDICO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel2.setText("Número de Palabras");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        txtNumeroDePalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDePalabrasActionPerformed(evt);
            }
        });
        txtNumeroDePalabras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDePalabrasKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumeroDePalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 60, -1));

        jLabel3.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel3.setText("Tamaño en cm");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        txtTamañoEnCm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamañoEnCmKeyTyped(evt);
            }
        });
        getContentPane().add(txtTamañoEnCm, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 60, -1));

        jLabel4.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel4.setText("Número de Colores");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        txtNumeroDeColores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDeColoresKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumeroDeColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 60, -1));

        jLabel5.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel5.setText("Valor Palabras");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtValorPalabras.setEditable(false);
        getContentPane().add(txtValorPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, -1));

        jLabel6.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel6.setText("Valor Tamaño ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        txtValorTamaño.setEditable(false);
        getContentPane().add(txtValorTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, -1));

        jLabel7.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel7.setText("Valor Colores");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        txtValorColores.setEditable(false);
        getContentPane().add(txtValorColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 110, -1));

        cmbCalcular.setText("CALCULAR");
        cmbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        cmbBorrar.setText("BORRAR");
        cmbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel8.setText("Valor Total A Pagar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));
        getContentPane().add(txtValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroDePalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDePalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDePalabrasActionPerformed

    private void cmbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCalcularActionPerformed
        // TODO add your handling code here:
        String  num1, num2,num3, resul, resul1, resul2, tota;
        double n1 = 1,n2 = 1,n3 = 1,resultado = 0, npalabras,ntamaños,ncolores, total;
        
        
        
        if (txtNumeroDePalabras.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite la cantidad de palabras ", "Error",JOptionPane.ERROR_MESSAGE);
        txtNumeroDePalabras.requestFocusInWindow();
        } else if (txtTamañoEnCm.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite el tamaño en cm", "Error",JOptionPane.ERROR_MESSAGE);
        txtTamañoEnCm.requestFocusInWindow();
        if (txtNumeroDeColores.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite el numero de colores", "Error",JOptionPane.ERROR_MESSAGE);
        txtNumeroDeColores.requestFocusInWindow();
        }
        }else {
        
           
        n1= Double.parseDouble(txtNumeroDePalabras.getText());
        n2= Double.parseDouble(txtTamañoEnCm.getText());
        n3 = Double.parseDouble(txtNumeroDeColores.getText());
        
        }
        
        npalabras = n1*20000;
        resul = String.valueOf(npalabras);
        txtValorPalabras.setText(resul);
        
        ntamaños = n2*15000;
        resul1= String.valueOf(ntamaños);
        txtValorTamaño.setText(resul1);
        
        ncolores = n3*25000;
        resul2= String.valueOf(ncolores);
        txtValorColores.setText(resul2);
        
        total = npalabras+ntamaños+ncolores;
        tota= String.valueOf(total);
        txtValorTotal.setText(tota);
        
        
        
        
        
    }//GEN-LAST:event_cmbCalcularActionPerformed

    private void cmbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBorrarActionPerformed
        // TODO add your handling code here:
        
        txtNumeroDePalabras.setText("");
        txtTamañoEnCm.setText("");
        txtNumeroDeColores.setText("");
        txtValorPalabras.setText("");
        txtValorTamaño.setText("");
        txtValorColores.setText("");
        txtValorTotal.setText("");
        
        
        
       txtNumeroDePalabras.requestFocusInWindow();
    }//GEN-LAST:event_cmbBorrarActionPerformed

    private void txtNumeroDePalabrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDePalabrasKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
          } 
    }//GEN-LAST:event_txtNumeroDePalabrasKeyTyped

    private void txtTamañoEnCmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamañoEnCmKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
          } 
    }//GEN-LAST:event_txtTamañoEnCmKeyTyped

    private void txtNumeroDeColoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDeColoresKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
          } 
    }//GEN-LAST:event_txtNumeroDeColoresKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbBorrar;
    private javax.swing.JButton cmbCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtNumeroDeColores;
    private javax.swing.JTextField txtNumeroDePalabras;
    private javax.swing.JTextField txtTamañoEnCm;
    private javax.swing.JTextField txtValorColores;
    private javax.swing.JTextField txtValorPalabras;
    private javax.swing.JTextField txtValorTamaño;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
